# Generated by Django 5.0 on 2024-02-16 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_menu_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
